plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	/* ---------- CORE ---------- */
	implementation 'org.springframework.boot:spring-boot-starter-web'         // REST
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'    // JPA/Hibernate
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.hibernate.orm:hibernate-spatial'
// DB migrations

	/* ---------- DATABASE ---------- */
	runtimeOnly   'org.postgresql:postgresql'                                  // JDBC driver
//	implementation 'org.hibernate:hibernate-spatial'                           // PostGIS types
	implementation 'org.locationtech.jts:jts-core:1.19.0'                      // Geometry helpers

	/* ---------- JSON binding ---------- */
	implementation 'com.fasterxml.jackson.core:jackson-databind'

	/* ---------- LOMBOK (optional) ---------- */
	compileOnly   'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	/* ---------- TEST ---------- */
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly   'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
